AWSTemplateFormatVersion: '2010-09-09'
Description: new test template
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small or etc..
Resources:
  myec2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      ImageId: ami-1853ac65
      Tags:
          -
            Key: "Name"
            Value: "WEBSERVER08"
      KeyName: 'testvpc'
      BlockDeviceMappings:
          - DeviceName: '/dev/sdm'
            Ebs:
              VolumeType: 'gp2'
              VolumeSize: 10
