AWSTemplateFormatVersion: 2010-09-09
Resources:
  MYVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 20.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: PRODVPC
  PUBLICSUBNET1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MYVPC
      CidrBlock: 20.0.1.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: PUBLICSUBNET1A
  PUBLICSUBNET2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MYVPC
      CidrBlock: 20.0.2.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: PUBLICSUBNET2A
  MYELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
      - "us-east-1a"
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      Tags:
      - Key: Name
        Value: ELASTICLB
  MYDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: barneslab.com.
      Comment: Zone apex alias targeted to myELB LoadBalancer.
      RecordSets:
      - Name: miketest.barneslab.com.
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt MYELB.CanonicalHostedZoneNameID
          DNSName: !GetAtt MYELB.DNSName
      Tags:
      - Key: Name
        Value: DNS