AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Sub '14.250.0.0/16'
  SubnetAPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '14.250.1.0/24'
      VpcId: !Ref VPC

Outputs:
  Subnet:
    Description: 'Subnet.'
    Value: !Ref SubnetAPublic
    Export:
      Name: 'vpc-subnet'